#!/usr/bin/env python
import decimal
from decimal import Decimal

A =Decimal(input("Introduzca el numero A: "))
B = Decimal(input("Introduzca el numero B: "))
C = Decimal(input("Introduzca el numero C: "))

operacion1 = 0
operacion2 = 0 
contador = 2

#Si A/B > 30,calculara e imprimira A/C * B^3
if Decimal(A)/Decimal(B) > 30:
    operacion1 = (Decimal(A)/Decimal(C))*(Decimal(B)**3)
print "Apartado 1: ", operacion1

#Si A/B <= 30, calculara e imprimira 2^2+4^2+6^2+...+30^2
if A/B <= 30:
    while contador != 32:
        operacion2 += contador**2
        contador += 2
print "Apartado 2: " , operacion2
